def randint(*_1, **_2): ...
def rand(*_1, **_2): ...
def get_state(): ...
def set_state(*_1,**_2): ...
def permutation(*_1,**_2): ...
def choice(*_1,**_2): ...
def RandomState(*_1,**_2):...
def normal(*_1, **_2): ...
