def randint(*_1, **_2): ...
def rand(*_1, **_2): ...
def get_state(): ...
def set_state(*_1,**_2): ...
def permutation(*_1,**_2): ...
def choice(*_1,**_2): ...
def normal(*_1, **_2): ...
def poisson(*_1, **_2): ...
def seed(self, *_1, **_2): ...

class RandomState:
    def __init__(self, *_1, **_2): ...
    def randint(self, *_1, **_2): ...
    def rand(self, *_1, **_2): ...
    def permutation(self, *_1,**_2): ...
    def choice(self, *_1,**_2): ...
    def normal(self, *_1, **_2): ...
    def poisson(self, *_1, **_2): ...
